const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'My API Documentation',
      version: '1.0.0',
      description: 'Auto-generated by swagger-jsdoc',
    },
    servers: [
      {
        url: 'http://localhost:8000', // change if needed
      },
    ],
  },
  apis: ['./src/v1/routes/*.js'], // path to route files with swagger comments
};

const specs = swaggerJsdoc(options);

module.exports = {
  swaggerUi,
  specs,
};
